[package]
name = "mokume-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Command line interface for mokume"

[[bin]]
name = "mokume"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
csv = "1.4.0"
hdf5-metno = { version = "0.13.0", features = ["static"] }
ndarray = "0.17"
mokume-core = { path = "../mokume-core" }
mokume-io = { path = "../mokume-io" }
mokume-pipeline = { path = "../mokume-pipeline" }
mokume-stats = { version = "0.1.0", path = "../mokume-stats" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
tempfile = "3"
